/datum/unit_test/craftable_hardset_sellprice/Run()
	var/list/grandfathered = list(
		/obj/item/alch/feaudust,
		/obj/item/alch/magicdust,
		/obj/item/alch/transisdust,
		/obj/item/clothing/head/roguetown/headdress,
		/obj/item/clothing/head/roguetown/papakha/crafted,
		/obj/item/clothing/neck/roguetown/leather,
		/obj/item/clothing/neck/roguetown/psicross/abyssor/g,
		/obj/item/clothing/neck/roguetown/psicross/astrata/g,
		/obj/item/clothing/neck/roguetown/psicross/bpearl,
		/obj/item/clothing/neck/roguetown/psicross/dendor/g,
		/obj/item/clothing/neck/roguetown/psicross/eora/g,
		/obj/item/clothing/neck/roguetown/psicross/g,
		/obj/item/clothing/neck/roguetown/psicross/inhumen/baotha/g,
		/obj/item/clothing/neck/roguetown/psicross/inhumen/g,
		/obj/item/clothing/neck/roguetown/psicross/inhumen/graggar/g,
		/obj/item/clothing/neck/roguetown/psicross/inhumen/matthios/g,
		/obj/item/clothing/neck/roguetown/psicross/malum/g,
		/obj/item/clothing/neck/roguetown/psicross/necra/g,
		/obj/item/clothing/neck/roguetown/psicross/noc/g,
		/obj/item/clothing/neck/roguetown/psicross/pearl,
		/obj/item/clothing/neck/roguetown/psicross/pestra/g,
		/obj/item/clothing/neck/roguetown/psicross/ravox/g,
		/obj/item/clothing/neck/roguetown/psicross/reform/g,
		/obj/item/clothing/neck/roguetown/psicross/shell,
		/obj/item/clothing/neck/roguetown/psicross/shell/bracelet,
		/obj/item/clothing/neck/roguetown/psicross/silver,
		/obj/item/clothing/neck/roguetown/psicross/silver/astrata,
		/obj/item/clothing/neck/roguetown/psicross/silver/necra,
		/obj/item/clothing/neck/roguetown/psicross/silver/noc,
		/obj/item/clothing/neck/roguetown/psicross/silver/undivided,
		/obj/item/clothing/neck/roguetown/psicross/undivided/g,
		/obj/item/clothing/neck/roguetown/psicross/xylix/g,
		/obj/item/clothing/ring/active/nomag,
		/obj/item/clothing/ring/band,
		/obj/item/clothing/ring/band/bronze,
		/obj/item/clothing/ring/band/gold,
		/obj/item/clothing/ring/band/paalloy,
		/obj/item/clothing/ring/blacksteel,
		/obj/item/clothing/ring/dragon_ring,
		/obj/item/clothing/ring/statdorpel,
		/obj/item/clothing/suit/roguetown/armor/basiceast/crafteast,
		/obj/item/clothing/suit/roguetown/armor/leather/studded,
		/obj/item/clothing/suit/roguetown/armor/leather/studded/bikini,
		/obj/item/clothing/suit/roguetown/armor/leather/studded/cuirbouilli,
		/obj/item/clothing/suit/roguetown/armor/leather/studded/warden/upgraded,
		/obj/item/clothing/suit/roguetown/shirt/robe/merchant,
		/obj/item/clothing/wrists/roguetown/bracers/gold,
		/obj/item/clothing/wrists/roguetown/bracers/leather/heavy,
		/obj/item/dildo/gold,
		/obj/item/dildo/iron,
		/obj/item/dildo/silver,
		/obj/item/dildo/steel,
		/obj/item/dildo/wood,
		/obj/item/fishingrod/crafted,
		/obj/item/ingot/component/berserkswordblade,
		/obj/item/ingot/component/berserkswordgrip,
		/obj/item/ingot/component/heapofrawiron,
		/obj/item/listenstone,
		/obj/item/magic/fae/fairydust,
		/obj/item/magic/fae/heartwoodcore,
		/obj/item/magic/fae/iridescentscale,
		/obj/item/magic/fae/sylvanessence,
		/obj/item/natural/cloth,
		/obj/item/natural/cloth/bandage,
		/obj/item/natural/glassbatch,
		/obj/item/reagent_containers/food/snacks/grown/fruit/blackberry/skysugarbase,
		/obj/item/reagent_containers/food/snacks/rogue/meat/steak/gnoll,
		/obj/item/reagent_containers/food/snacks/rogue/meat/steak/vilespawn,
		/obj/item/reagent_containers/lux,
		/obj/item/reagent_containers/lux/moss,
		/obj/item/reagent_containers/powder/black_ichor,
		/obj/item/reagent_containers/powder/moondust,
		/obj/item/reagent_containers/powder/ozium,
		/obj/item/reagent_containers/powder/starsugar/skysugar,
		/obj/item/roguegem/blood_diamond,
		/obj/item/rogueore/coal,
		/obj/item/rogueore/gold,
		/obj/item/rogueore/iron,
		/obj/item/rogueweapon/hoe/aalloy,
		/obj/item/rogueweapon/huntingknife/idagger/silver/psydagger,
		/obj/item/rogueweapon/huntingknife/idagger/silver/psydagger/heavy,
		/obj/item/rogueweapon/huntingknife/idagger/stake,
		/obj/item/rogueweapon/huntingknife/throwingknife/silver,
		/obj/item/rogueweapon/mace/steel/silver/decorated,
		/obj/item/rogueweapon/pick/aalloy,
		/obj/item/rogueweapon/pitchfork/aalloy,
		/obj/item/rogueweapon/shield/heater/crafted,
		/obj/item/rogueweapon/shield/tower/holysee,
		/obj/item/rogueweapon/shovel/aalloy,
		/obj/item/rogueweapon/sickle/aalloy,
		/obj/item/rogueweapon/spellbook,
		/obj/item/rogueweapon/spellbook/grand,
		/obj/item/rogueweapon/spellbook/greater,
		/obj/item/rogueweapon/sword/blacksteel,
		/obj/item/rogueweapon/sword/blacksteel/decorated,
		/obj/item/rogueweapon/sword/gold,
		/obj/item/rogueweapon/thresher/aalloy,
		/obj/item/rogueweapon/woodstaff/implement,
		/obj/item/rogueweapon/woodstaff/implement/amethyst,
		/obj/item/rogueweapon/woodstaff/implement/grand,
		/obj/item/rogueweapon/woodstaff/implement/grand/blacksteel,
		/obj/item/rogueweapon/woodstaff/implement/grand/riddle,
		/obj/item/rogueweapon/woodstaff/implement/greater,
		/obj/item/rogueweapon/woodstaff/implement/greater/quartz,
		/obj/item/rogueweapon/woodstaff/implement/greater/ruby,
		/obj/item/rogueweapon/woodstaff/implement/greater/sapphire,
		/obj/item/runicflask/charged,
		/obj/item/storage/backpack/rogue/satchel/black,
		/obj/item/storage/belt/rogue/leather,
		/obj/item/storage/belt/rogue/leather/battleskirt,
		/obj/item/storage/belt/rogue/leather/battleskirt/breechcloth,
		/obj/item/storage/belt/rogue/leather/battleskirt/breechcloth/blackbelt,
		/obj/item/storage/belt/rogue/leather/battleskirt/faulds,
		/obj/item/storage/belt/rogue/leather/beltshawl,
		/obj/item/storage/belt/rogue/leather/black,
		/obj/item/storage/belt/rogue/leather/cloth,
		/obj/item/storage/belt/rogue/leather/cloth/upgraded,
		/obj/item/storage/belt/rogue/leather/double,
		/obj/item/storage/belt/rogue/leather/iron,
		/obj/item/storage/belt/rogue/leather/iron/tasset,
		/obj/item/storage/belt/rogue/leather/knifebelt,
		/obj/item/storage/belt/rogue/leather/plaquegold,
		/obj/item/storage/belt/rogue/leather/plaquesilver,
		/obj/item/storage/belt/rogue/leather/rope,
		/obj/item/storage/belt/rogue/leather/rope/upgraded,
		/obj/item/storage/belt/rogue/leather/sash,
		/obj/item/storage/belt/rogue/leather/sash/maid,
		/obj/item/storage/belt/rogue/leather/silkbelt,
		/obj/item/storage/belt/rogue/leather/steel,
		/obj/item/storage/belt/rogue/leather/steel/tasset,
		/obj/item/storage/belt/rogue/leather/suspenders,
		/obj/item/storage/roguebag/crafted,
		/obj/structure/closet/crate/chest/crafted,
		/obj/structure/closet/crate/chest/wicker,
		/obj/structure/fermentation_keg/crafted,
		/obj/structure/fermentation_keg/distiller,
	)

	var/list/offenders = list()
	for(var/datum/crafting_recipe/recipe as anything in GLOB.crafting_recipes)
		var/list/result_paths = islist(recipe.result) ? recipe.result : list(recipe.result)
		for(var/path in result_paths)
			check_result(path, "crafting recipe '[recipe.name]'", grandfathered, offenders)
	for(var/datum/anvil_recipe/recipe as anything in GLOB.anvil_recipes)
		check_result(recipe.created_item, "anvil recipe '[recipe.name]'", grandfathered, offenders)

	for(var/path in grandfathered)
		if(!offenders[path])
			TEST_NOTICE(src, "[path] is grandfathered in [type] but is no longer a craftable item with a hardset sellprice. Remove it from the grandfathered list.")

/datum/unit_test/craftable_hardset_sellprice/proc/check_result(path, source, list/grandfathered, list/offenders)
	if(!ispath(path, /atom/movable))
		return
	var/atom/movable/proto = path
	if(initial(proto.sellprice) <= 0)
		return
	if(offenders[path])
		return
	offenders[path] = TRUE
	if(path in grandfathered)
		return
	TEST_FAIL("Craftable item [path] (result of [source]) has a hardset sellprice = [initial(proto.sellprice)]. Remove the item's sellprice (check its parent types - it may be inherited) so the pricing engine derives the value from the recipe's materials.")
